site_name: Cyber Defence Kit

nav:
  - Home: index.md
  - About CDK:
    - Cyber Defence Kit Explained: CDK-explained/CDK-explained.md
  - SIEM:
    - Understanding SIEM: understanding-SIEM/understanding-SIEM.md
    - Splunk: splunk/splunk.md
    - Wazuh: wazuh/wazuh.md
  - IDS/IPS:
    - Understanding IDS/IPS: understanding-IDS-IPS/understanding-IDS-IPS.md 
    - Snort: snort/snort.md
    - Suricata: suricata/suricata.md
  - SIRP:
    - Understanding SIRP: understanding-SIRP/understanding-SIRP.md 
    - TheHive: thehive/thehive.md
    - IRIS: iris/iris.md
  - SOAR:
    - Understanding SOAR: understanding-SOAR/understanding-SOAR.md 
    - Shuffle: shuffle/shuffle.md
  - NTA:
    - Understanding NTA: understanding-NTA/understanding-NTA.md 
    - Wireshark: wireshark/wireshark.md
    - Zeek: zeek/zeek.md
    - Zui: zui/zui.md
  - DFIR:
    - Understanding DFIR: understanding-DFIR/understanding-DFIR.md
    - Velociraptor: velociraptor/velociraptor.md
  - EDR:
    - Understanding EDR: understanding-EDR/understanding-EDR.md
    - Aurora Lite: auroralite/auroralite.md


theme:
  name: material
  logo: images/Cyber Defence Kit logo.png
  favicon: images/Cyber Defence Kit logo.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: light blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: light blue
plugins:
  - social
  - search
  - glightbox
  - offline

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cyberdefencekit

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - md_in_html
  - tables
  - toc:
      title: On this page
  
copyright: |
  &copy; 2024 <a href="https://github.com/cyberdefencekit"  target="_blank" rel="noopener">Cyber Defence Kit - Joseph Jee</a>
